
name: Flutter Web
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.secret_token}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email laura.trivino@wanadoo.fr
          git config --global user.name Drakadriel
          git status
          git remote add origin https://${{secrets.secret_token}}@github.com/Drakadriel/Drakadriel.github.io.git
          git checkout -b master
          git add --all
          git commit -m "update"
          git push origin master -f
